from flask import Flask, render_template, request, redirect, url_for, send_file
import os
from werkzeug.utils import secure_filename
from openpyxl import Workbook
import pandas as pd
import sqlite3
import matplotlib
from reportlab.pdfgen import canvas
matplotlib.use("Agg")
import matplotlib.pyplot as plt

app = Flask(__name__)

# ===========================
# LOGIN
# ===========================

@app.route("/")
def index():
    return redirect(url_for("login"))


@app.route("/login", methods=["GET", "POST"])
def login():

    error = ""

    if request.method == "POST":

        username = request.form["username"]
        password = request.form["password"]

        if username == "admin" and password == "1234":
            return redirect(url_for("home"))
        else:
            error = "Invalid Username or Password"

    return render_template("login.html", error=error)


# ===========================
# ADD PATIENT
# ===========================

@app.route("/add", methods=["POST"])
def add_patient():

    conn = sqlite3.connect("health.db")
    cursor = conn.cursor()
    photo = request.files["photo"]

if photo.filename != "":
    filename = secure_filename(photo.filename)
    photo.save(os.path.join("static", "uploads", filename))
else:
    filename = ""

    cursor.execute("""
    INSERT INTO patients
    (Patient_ID, Age, Gender, Height_cm, Weight_kg, Systolic_BP, Diastolic_BP, Photo)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
""", (
    request.form["Patient_ID"],
    request.form["Age"],
    request.form["Gender"],
    request.form["Height_cm"],
    request.form["Weight_kg"],
    request.form["Systolic_BP"],
    request.form["Diastolic_BP"],
    filename
))
        request.form["Patient_ID"],
        request.form["Age"],
        request.form["Gender"],
        request.form["Height_cm"],
        request.form["Weight_kg"],
        request.form["Systolic_BP"],
        request.form["Diastolic_BP"]
    ))

    conn.commit()
    conn.close()

    return redirect(url_for("home"))


# ===========================
# DELETE PATIENT
# ===========================
@app.route("/edit/<int:patient_id>", methods=["GET", "POST"])
def edit_patient(patient_id):

    conn = sqlite3.connect("health.db")
    cursor = conn.cursor()

    if request.method == "POST":

        cursor.execute("""
            UPDATE patients
            SET Age=?,
                Gender=?,
                Height_cm=?,
                Weight_kg=?,
                Systolic_BP=?,
                Diastolic_BP=?
            WHERE Patient_ID=?
        """, (
            request.form["Age"],
            request.form["Gender"],
            request.form["Height_cm"],
            request.form["Weight_kg"],
            request.form["Systolic_BP"],
            request.form["Diastolic_BP"],
            patient_id
        ))

        conn.commit()
        conn.close()

        return redirect(url_for("home"))

    patient = cursor.execute(
        "SELECT * FROM patients WHERE Patient_ID=?",
        (patient_id,)
    ).fetchone()

    conn.close()

    return render_template("edit.html", patient=patient)

@app.route("/delete/<int:patient_id>")
def delete_patient(patient_id):

    conn = sqlite3.connect("health.db")
    cursor = conn.cursor()

    cursor.execute(
        "DELETE FROM patients WHERE Patient_ID = ?",
        (patient_id,)
    )

    conn.commit()
    conn.close()

    return redirect(url_for("home"))
# ===========================
# DOWNLOAD PDF
# ===========================

@app.route("/download_pdf")
def download_pdf():

    conn = sqlite3.connect("health.db")
    cursor = conn.cursor()

    data = cursor.execute(
        "SELECT * FROM patients"
    ).fetchall()

    conn.close()

    pdf = canvas.Canvas("Health_Report.pdf")

    # Title
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(170, 800, "Health Check-Up Report")

    pdf.setFont("Helvetica", 11)
    pdf.drawString(30, 780, "Generated by Health Check-Up Dashboard")

    pdf.line(20, 770, 580, 770)

    # Table Heading
    pdf.setFont("Helvetica-Bold", 9)

    pdf.drawString(20, 750, "ID")
    pdf.drawString(60, 750, "Age")
    pdf.drawString(95, 750, "Gender")
    pdf.drawString(150, 750, "Height")
    pdf.drawString(220, 750, "Weight")
    pdf.drawString(290, 750, "Sys BP")
    pdf.drawString(350, 750, "Dia BP")
    pdf.drawString(420, 750, "BMI")
    pdf.drawString(470, 750, "BP")

    y = 730

    pdf.setFont("Helvetica", 9)

    # Patient Data
    for row in data:

        height = row[3] / 100
        bmi = round(row[4] / (height * height), 2)

        if row[5] < 120 and row[6] < 80:
            bp = "Normal"
        elif row[5] < 130 and row[6] < 80:
            bp = "Elevated"
        elif row[5] < 140 or row[6] < 90:
            bp = "Stage1"
        else:
            bp = "Stage2"

        pdf.drawString(20, y, str(row[0]))
        pdf.drawString(60, y, str(row[1]))
        pdf.drawString(95, y, str(row[2]))
        pdf.drawString(150, y, str(row[3]))
        pdf.drawString(220, y, str(row[4]))
        pdf.drawString(290, y, str(row[5]))
        pdf.drawString(350, y, str(row[6]))
        pdf.drawString(420, y, str(bmi))
        pdf.drawString(470, y, bp)

        y -= 20

        if y < 50:
            pdf.showPage()
            pdf.setFont("Helvetica", 9)
            y = 800

    pdf.save()

    return send_file(
        "Health_Report.pdf",
        as_attachment=True
    )
# ===========================
# DOWNLOAD EXCEL
# ===========================

@app.route("/download_excel")
def download_excel():

    conn = sqlite3.connect("health.db")
    cursor = conn.cursor()

    data = cursor.execute("SELECT * FROM patients").fetchall()

    conn.close()

    wb = Workbook()
    ws = wb.active
    ws.title = "Patients"

    ws.append([
        "Patient ID",
        "Age",
        "Gender",
        "Height (cm)",
        "Weight (kg)",
        "Systolic BP",
        "Diastolic BP"
    ])

    for row in data:
        ws.append(row)

    wb.save("Health_Report.xlsx")

    return send_file(
        "Health_Report.xlsx",
        as_attachment=True
    )
# ===========================
# LOGOUT
# ===========================

@app.route("/logout")
def logout():
    return redirect(url_for("login"))



# ===========================
# DASHBOARD
# ===========================

@app.route("/dashboard")
def home():

    conn = sqlite3.connect("health.db")
    df = pd.read_sql_query("SELECT * FROM patients", conn)
    conn.close()

    search = request.args.get("search", "")

    if search:
        df = df[
            df["Patient_ID"].astype(str).str.contains(search, case=False)
            | df["Gender"].astype(str).str.contains(search, case=False)
        ]

    df["Height_m"] = df["Height_cm"] / 100
    df["BMI"] = (df["Weight_kg"] / (df["Height_m"] ** 2)).round(2)

    def bmi_category(bmi):
        if bmi < 18.5:
            return "Underweight"
        elif bmi < 25:
            return "Normal"
        elif bmi < 30:
            return "Overweight"
        else:
            return "Obese"

    df["BMI_Category"] = df["BMI"].apply(bmi_category)

    def bp_status(sys, dia):
        if sys < 120 and dia < 80:
            return "Normal"
        elif sys < 130 and dia < 80:
            return "Elevated"
        elif sys < 140 or dia < 90:
            return "High BP Stage 1"
        else:
            return "High BP Stage 2"

    df["BP_Status"] = df.apply(
        lambda x: bp_status(
            x["Systolic_BP"],
            x["Diastolic_BP"]
        ),
        axis=1
    )

    total_patients = len(df)
    avg_bmi = round(df["BMI"].mean(), 2)
    avg_age = round(df["Age"].mean(), 1)

    bmi_counts = df["BMI_Category"].value_counts()

    plt.figure(figsize=(5,5))
    plt.pie(
        bmi_counts,
        labels=bmi_counts.index,
        autopct="%1.1f%%",
        startangle=90
    )
    plt.title("BMI Category Distribution")
    plt.savefig("static/bmi_chart.png")
    plt.close()

    return render_template(
        "index.html",
        total_patients=total_patients,
        avg_bmi=avg_bmi,
        avg_age=avg_age,
        data=df.to_dict(orient="records"),
        search=search
    )


if __name__ == "__main__":
    app.run(debug=True)
    